[sources.quad9-resolvers-dnscrypt]
urls = ["https://quad9.net/dnscrypt/quad9-resolvers-dnscrypt.md", "https://raw.githubusercontent.com/Quad9DNS/dnscrypt-settings/main/dnscrypt/quad9-resolvers-dnscrypt.md"]
minisign_key = "RWTp2E4t64BrL651lEiDLNon+DqzPG4jhZ97pfdNkcq1VDdocLKvl5FW"
cache_file = "quad9-resolvers-dnscrypt.md"
refresh_delay = 72
prefix = "quad9-"

